Create first 3 blocks
nikolaevigor/yard-frontend pull request #1
Opened 2017-06-13 12:54 UTC by nikolaevigor

Проверь пока что есть, пожалуйста

2017-06-13 12:59 UTC, nikolaevigor commented
Неожиданно быстро сверстал карточки

2017-06-13 13:05 UTC, imevro requested changes
https://rawgit.com/nikolaevigor/yard-frontend/develop/complexes.html
1) размер шапки не тот
2) отступы между карточками
3) отступы в карточке
4) блок с discover неправильно свёрстан

https://validator.w3.org/nu/?doc=https%3A%2F%2Frawgit.com%2Fnikolaevigor%2Fyard-frontend%2Fdevelop%2Fcomplexes.html

2017-06-13 21:20 UTC, imevro requested changes
Отступы в футере не как в макете

2017-06-13 22:04 UTC, nikolaevigor commented
@evgenyrodionov отступы флексбоксгридовые?

2017-06-14 13:28 UTC, imevro requested changes
Хорошо, но ↓

И в футере отступы между ссылками не те и у копирайт-нотиса лайн-хейт не тот

2017-06-14 13:28 UTC, evgenyrodionov commented on complexes.html
> +              <a class="footer-link footer-apartment-link" href="#">ВТБ Арена Парк</a>
это не апартмент линк, это просто ссылка

2017-06-14 13:28 UTC, evgenyrodionov commented on complexes.html
> +            <div class="col-xs-offset-0 col-xs-2">
а зачем оффсет 0

2017-06-14 13:34 UTC, nikolaevigor commented on complexes.html
> +            <div class="col-xs-offset-0 col-xs-2">
потому что от нулевой колонки влево 2 штуки @evgenyrodionov

2017-06-14 13:35 UTC, evgenyrodionov commented on complexes.html
> +            <div class="col-xs-offset-0 col-xs-2">
не понял

2017-06-14 13:35 UTC, evgenyrodionov commented on complexes.html
> +            <div class="col-xs-offset-0 col-xs-2">
у тебя и так по-умолчанию оффсет не задается, зачем эксклюзивно тут писать оффсет-0

2017-06-14 13:36 UTC, nikolaevigor commented on complexes.html
> +            <div class="col-xs-offset-0 col-xs-2">
не знал об этом, уберу

2017-06-14 13:45 UTC, nikolaevigor commented on complexes.html
> +              <a class="footer-link footer-apartment-link" href="#">ВТБ Арена Парк</a>
не понял. нейминг неправильный? в стилях надо было навесить для колонки жилых комплексов на ластчайлд то, что не надо было навешивать на соседнюю справа колонку. @evgenyrodionov

2017-06-14 13:48 UTC, evgenyrodionov commented on complexes.html
> +              <a class="footer-link footer-apartment-link" href="#">ВТБ Арена Парк</a>
Не проще на последнюю ссылку завести класс?

2017-06-14 14:08 UTC, nikolaevigor commented
@evgenyrodionov не понял, какие конкретно отступы?
![photo_2017-06-14_17-07-18](https://user-images.githubusercontent.com/3702281/27136440-fe503212-5123-11e7-919a-95e15044448a.jpg)
Вот эти точно по цеплину 8px и 16px

2017-06-14 14:16 UTC, nikolaevigor commented
Поправил лайнхайты. Думаю это то, что ты имел в виду. @evgenyrodionov

2017-06-14 19:23 UTC, imevro requested changes

2017-06-14 19:23 UTC, evgenyrodionov commented on complexes.html
> +    <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
Не нужно делать 3 запроса, объедини в один, в гфонтс можно

2017-06-14 19:23 UTC, evgenyrodionov commented on style.css
> +  margin: 20px 120px 20px 0;
если засунешь в контейнер, то не нужно будет марджин справа ебашить. Смотри, что получается, если открыть на большом экране https://www.dropbox.com/s/p5i989ou0peqe3s/Screenshot%202017-06-14%2022.20.38.png?dl=0

2017-06-14 19:23 UTC, evgenyrodionov commented on style.css
> +  margin: 20px 0 20px 120px;
тоже самое про марджин

2017-06-14 19:23 UTC, evgenyrodionov commented on style.css
> +  margin: 80px 511px;
используй авто чтобы не прописывать марджин слева и справа

2017-06-14 19:23 UTC, evgenyrodionov commented on style.css
> +  padding: 24px 32px 0 32px;
почему отступ слева 0?

2017-06-14 19:23 UTC, evgenyrodionov commented on style.css
> +  padding: 32px 128px 28px 128px;
зачем паддинги слева и справа? контейнер этим занимается сам

2017-06-14 19:23 UTC, evgenyrodionov commented on style.css
> +  margin: 96px 0 0 0;
пропиши просто марджин-топ

2017-06-14 19:36 UTC, nikolaevigor commented on style.css
> +  padding: 24px 32px 0 32px;
это отсуп снизу
исправить?
@evgenyrodionov

2017-06-14 21:09 UTC, imevro approved these changes

2017-06-14 21:09 UTC, evgenyrodionov commented on complexes.html
> +            <div class="col-lg-offset-0 col-lg-2">
камон

2017-06-14 21:25 UTC, merged