Add hooks; fix some lint errors
nikolaevigor/yard-frontend pull request #12
Opened 2017-06-26 13:58 UTC by nikolaevigor

https://yard-frontend-zszfhpzivd.now.sh

2017-06-26 17:28 UTC, imevro requested changes

2017-06-26 17:28 UTC, evgenyrodionov commented on package.json
> +    "precommit": "eslint src/ —ext .jsx —ext .js"
а зачем

2017-06-26 17:28 UTC, evgenyrodionov commented on package.json
> +    "prepush": "eslint src/ —ext .jsx —ext .js",
-ext разве так работает? Там два -- и через запятую

2017-06-26 17:28 UTC, evgenyrodionov commented on src/index.js
> +ReactDOM.render(<App />, document.getElementById('root')); // eslint-disable-line
почему?

2017-06-26 17:29 UTC, nikolaevigor commented on package.json
> +    "precommit": "eslint src/ —ext .jsx —ext .js"
чтобы коммитить чисто сразу, так удобнее на мой взгляд @evgenyrodionov

2017-06-26 17:30 UTC, nikolaevigor commented on src/index.js
> +ReactDOM.render(<App />, document.getElementById('root')); // eslint-disable-line
@evgenyrodionov ругается на то, что документ андифайнд

2017-06-26 17:32 UTC, evgenyrodionov commented on src/index.js
> +ReactDOM.render(<App />, document.getElementById('root')); // eslint-disable-line
так пофикси

2017-06-26 21:35 UTC, imevro requested changes

2017-06-26 21:35 UTC, evgenyrodionov commented on package.json
> +    "prepush": "eslint src/ --ext .jsx, .js",
да нет же, `--ext=js,jsx`

2017-06-26 21:39 UTC, evgenyrodionov commented on package.json
> +    "prepush": "eslint src/ --ext .jsx, .js",
Неправ, но после запятой вроде не нужна запятая

2017-06-27 09:20 UTC, imevro approved these changes

2017-06-27 09:21 UTC, merged