Прикуртил api запросы для первой страницы
nikolaevigor/yard-frontend pull request #13
Opened 2017-06-27 16:43 UTC by nikolaevigor

2017-06-27 17:19 UTC, imevro requested changes

2017-06-27 17:19 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +    this.setState({ imageBaseUrl: 'https://images.jqestate.ru/{id}-jqestate-{heightSize}' });
нет нужды это держать в стейте, заведи себе функцию под это и всё

2017-06-27 17:19 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +    let imgUrl = this.state.imageBaseUrl.replace('{id}', complex.images[0].id);
мутабельность запрещена

2017-06-27 17:19 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +              {this.renderCards()}
выводи мап здесь

2017-06-27 17:19 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +              {this.renderCards()}
и да, тут достаточно мапа без всех проверок

http://2ality.com/2015/01/es6-destructuring.html почитай про это и обрати внимание на дефолт вельюс

2017-06-27 20:03 UTC, nikolaevigor commented
https://nikolaevigor-yard.now.sh

2017-06-27 23:03 UTC, imevro requested changes

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +      <Geo>{props.geo.toUpperCase()}</Geo>
через цсс

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +  let imgUrl = getImgBaseUrl().replace('{id}', complex.images[0].id);
мутабельность запрещена, напоминаю

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +  return 'https://images.jqestate.ru/{id}-jqestate-{heightSize}';
1) если ты оперируешь строкой, зачем тебе функция которая её возвращает
2) почему ты в эту функцию не можешь спускать айди и размер аргументом?

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +        this.setState(json);
не очень очевидно что в итоге будет в стейте

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +                  geo={formatLocation(complex.location)}
geo={location}, не очень очевидно, соблюдай консистентность

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +                  title={complex.name}
title={name} та же ошибка что и ниже

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/Show/ApartmentHeader.jsx
> +          <Geo>{props.subtitle}</Geo>
subTitle всё-таки

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/Show/ImageCarousel.jsx
> +function getImageURL(id) {
если функция повторяется, выносишь её в хелпер (оно же утилс)

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/Show/ImageCarousel.jsx
> +  return 'https://images.jqestate.ru/{id}-jqestate-512'.replace('{id}', id);
es6 interpolation strings оно же template literals

либо контактенация как в старые добрые

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/Show/ImageCarousel.jsx
> +  return 'https://images.jqestate.ru/{id}-jqestate-512'.replace('{id}', id);
но уже лучше чем выше в списке, да

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +    const { subLocalityName = '', street = '', house = '', postalCode = '' } = location;
а зачем пустые строки

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +    return `${[subLocalityName, street, house].join(', ')} • ${postalCode}`;
выглядит как ебаная наскальная живопись

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +    return `${[subLocalityName, street, house].join(', ')} • ${postalCode}`;
не делай вычисления в строке

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +    const { images = [], name: title = 'Title is missing', statistics = {} } = this.state;
охуенный тайтл, вери продакт-ориентированный

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +    return (
отдельняй ретёрн от констант пустой строкой

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +          <ImageCarouesel imageIDs={images.map(image => image.id)} />
ImageCarouesel?

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +          <ImageCarouesel imageIDs={images.map(image => image.id)} />
imageIDs → imageIds, красивее выглядит

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +  getSubtitle() {
зачем эта функция в классе? вынеси в обычную

2017-06-27 23:03 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +  getSubtitle() {
или вообще в компонент ебани

2017-06-27 23:04 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27613758-1b90a01e-5ba6-11e7-8d4d-0d100e9572ea.png)

2017-06-27 23:05 UTC, evgenyrodionov commented
10/10 по шкале сжатости шакалов

![image](https://user-images.githubusercontent.com/775692/27613790-4a4d650e-5ba6-11e7-9304-00be08c6a5d2.png)

2017-06-28 09:35 UTC, nikolaevigor commented
https://nikolaevigor-yard.now.sh

2017-06-28 10:37 UTC, imevro requested changes

2017-06-28 10:37 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +  return `https://images.jqestate.ru/${complex.images[0].id}-jqestate-512`;
зачем передавать комлекс если можно передавать объект с картинкой

2017-06-28 10:37 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
>      fetch('https://api.jqestate.ru/v1/complexes?filter[state]=public')
https://github.com/boldyrev-d/yard-frontend/pull/7#discussion_r124506424

2017-06-28 10:37 UTC, evgenyrodionov commented on src/Complexes/Show/ApartmentHeader.jsx
> +  if (location.postalCode != null) {
1. не !=, а !==
2. используй оператор &&

2017-06-28 10:37 UTC, evgenyrodionov commented on src/Complexes/Show/ImageCarousel.jsx
> +        <Image key={id} src={`https://images.jqestate.ru/${id}-jqestate-512`} alt="Image" />,
поч тут нету гетимагеурл?

2017-06-28 10:37 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +    const { location = {} } = this.state;
а почему не в 28 строчке

2017-06-28 15:14 UTC, nikolaevigor commented
задеплоил на тот же урл

2017-06-28 18:08 UTC, imevro requested changes

2017-06-28 18:08 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +      this.setState({ items: json.items });
дестрактом!

2017-06-28 18:08 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +      this.setState({ items: json.items });
Будет очень красиво

2017-06-28 18:08 UTC, evgenyrodionov commented on src/Complexes/Show/ApartmentHeader.jsx
> +  if (location.postalCode == null) {
===

2017-06-28 18:08 UTC, evgenyrodionov commented on src/Complexes/Show/ApartmentHeader.jsx
> +  if (location.postalCode == null) {
Либо !!

2017-06-28 18:08 UTC, evgenyrodionov commented on src/Complexes/Show/ApartmentHeader.jsx
> +  if (location.postalCode == null) {
weak typing запрещен и еслинт должен тебе об этом сказать

2017-06-28 18:08 UTC, evgenyrodionov commented on src/api.js
> +function performGetRequest(query) {
ооооо джава

2017-06-28 18:08 UTC, evgenyrodionov commented on src/api.js
> +function performGetRequest(query) {
чё так сложно

2017-06-28 18:08 UTC, evgenyrodionov commented on src/api.js
> +  return fetch(`https://api.jqestate.ru/v1${query}`).then(response => response.json());
адрес вынеси в константу чтобы не дублировать

2017-06-28 18:08 UTC, evgenyrodionov commented on src/api.js
> +  return fetch(`https://api.jqestate.ru/v1${query}`).then(response => response.json());
респонс упрости до рес

2017-06-28 22:01 UTC, imevro requested changes

2017-06-28 22:01 UTC, evgenyrodionov commented on src/Complexes/Show/ApartmentHeader.jsx
>      return locationBase;
можно в одну строчку тогда уж вместе с ифом

2017-06-28 22:01 UTC, evgenyrodionov commented on src/api.js
> +function get(query) {
это ресурс, не квери

2017-06-28 22:01 UTC, evgenyrodionov commented on src/api.js
> +export { get, post };
можно сразу export function get

2017-06-29 10:13 UTC, imevro requested changes

2017-06-29 10:13 UTC, evgenyrodionov commented on src/Complexes/Show/ApartmentHeader.jsx
> +  if (location.postalCode) return `${locationBase} • ${location.postalCode}`;
делай отступы между константами и кодом

2017-06-29 10:13 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
>    componentDidMount() {
смотри, вот тебе кейс: мы добавляем блок ПОХОЖИЕ ЖИЛЫЕ КОМПЛЕКСЫ внизу страницы. Перехожу я с Полянки/44 на ВТБ Арена Парк, компонент тот же самый. Что произойдет?

2017-06-29 10:13 UTC, evgenyrodionov commented
тут слиплось почему-то

![image](https://user-images.githubusercontent.com/775692/27682858-c5233070-5ccc-11e7-9ed3-9efd528e367a.png)

2017-06-29 12:47 UTC, nikolaevigor commented
Задеплоил

2017-06-29 13:04 UTC, imevro requested changes

2017-06-29 13:04 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +const FirstRowFeature = Feature.extend`
чё-то какой-то костыль

2017-06-29 13:16 UTC, merged