Add flow integration
nikolaevigor/yard-frontend pull request #14
Opened 2017-06-30 12:22 UTC by nikolaevigor

2017-06-30 13:44 UTC, imevro requested changes

2017-06-30 13:44 UTC, evgenyrodionov commented on .env
> +PUBLIC_URL=http://localhost:3000
бля как эти файлы оказались в репозитории? они в гитигноре должны быть, кра так и делает

2017-06-30 13:44 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +  state: Object;
Распиши

2017-06-30 13:44 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +  constructor(props: Object) {
И тут тоже распиши

2017-06-30 13:44 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +export default ({ propertiesCount }: { propertiesCount: string }) =>
вынеси в тайп

2017-06-30 13:44 UTC, evgenyrodionov commented on src/Complexes/Show/ImageCarousel.jsx
> +export default ({ imageIds }: { imageIds: Array<string> }) =>
в тайп вынеси

2017-06-30 13:44 UTC, evgenyrodionov commented on src/Complexes/Show/Title.jsx
> +export default ({ children }: { children: Children }) => <Title>{children}</Title>;
опять же в тайп

2017-06-30 13:44 UTC, evgenyrodionov commented on src/api.js
> +export function get(resource: string) {
будет пиздато если ты заведешь енам

2017-06-30 19:01 UTC, imevro requested changes

2017-06-30 19:01 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +    items: Array<Object>,
распиши модель

2017-06-30 19:01 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +  items: Array<Object>;
wtf

2017-06-30 19:01 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
>    state: Object;
распиши модель

2017-06-30 21:27 UTC, imevro requested changes

2017-06-30 21:27 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +import type { item as itemType } from '../types';
PascalCase

2017-06-30 21:27 UTC, evgenyrodionov commented on src/Complexes/types.jsx
> +type item = {
PascaleCase опять же

2017-06-30 21:40 UTC, imevro requested changes

2017-06-30 21:40 UTC, evgenyrodionov commented on src/Complexes/types.jsx
> +type Item = {
итем хуитем, ю ноу

2017-07-01 09:08 UTC, imevro approved these changes

2017-07-01 09:10 UTC, merged