Add meaningful readme
nikolaevigor/yard-frontend pull request #15
Opened 2017-07-03 16:28 UTC by nikolaevigor

2017-07-03 20:00 UTC, imevro requested changes
Линт, флоу?

2017-07-03 22:31 UTC, imevro requested changes

2017-07-03 22:31 UTC, evgenyrodionov commented on README.md
> +    yarn run eslint src/ -- --ext .jsx,.js
закинь в пекейджс чтобы одной командой вызывать

2017-07-03 23:38 UTC, imevro requested changes

2017-07-03 23:38 UTC, evgenyrodionov commented on README.md
> +    yarn run eslint src/ -- --ext .jsx,.js
лол а тут

2017-07-04 09:33 UTC, imevro requested changes

2017-07-04 09:33 UTC, evgenyrodionov commented on README.md
> +Установить зависимости
Setting up

Установить зависимости

2017-07-04 09:33 UTC, evgenyrodionov commented on README.md
> +Установить зависимости
my english is very хорошо

2017-07-04 09:47 UTC, imevro requested changes

2017-07-04 09:47 UTC, evgenyrodionov commented on README.md
> +    yarn install
Ок, а где флоу-тайпед инсталл?

2017-07-04 11:12 UTC, nikolaevigor commented
пофиксил конфликты @evgenyrodionov

2017-07-04 13:03 UTC, merged