Add all blocks of complex.html except last
nikolaevigor/yard-frontend pull request #2
Opened 2017-06-16 01:58 UTC by nikolaevigor

Сделал все блоки, кроме последнего и пока что не сделал кнопку на карусельке с картинками.

2017-06-16 09:52 UTC, imevro requested changes
https://rawgit.com/nikolaevigor/yard-frontend/develop/complex.html

* интерлиньяж у описания не тот
* линии слишком жирные, должны быть 1 пкс
* 1-комнатные квартиры слишком чёрный шрифт

2017-06-16 09:53 UTC, evgenyrodionov commented
и кнопки нет "41 фотография"

2017-06-17 11:19 UTC, imevro requested changes

2017-06-17 11:19 UTC, evgenyrodionov commented on complex.html
> +    <hr class="complex-separation-line">
бордер-боттом для хедера

2017-06-17 11:19 UTC, evgenyrodionov commented on complex.html
> +        <header class="global-header-wrapper">
хедер в хедере нельзя

2017-06-17 11:19 UTC, evgenyrodionov commented on complex.html
> +        <h2 class="complex-summary-header">
это не хедер

2017-06-17 11:19 UTC, evgenyrodionov commented on complex.html
> +    <div class="container">
зачем плодить контейнеры, если несколько блоков можно обернуть в один?

2017-06-17 11:19 UTC, evgenyrodionov commented on complex.html
> +              <dl class="complex-feature-record">
а зачем постфикс -рекорд

2017-06-17 11:19 UTC, evgenyrodionov commented on complex.html
> +          <div class="complex-infrastructure-row-wrapper">
что за враппер оф враппер оф враппер оф враппер оф враппер оф враппер оф враппер оф враппер оф враппер оф враппер оф враппер оф враппер оф враппер оф враппер

2017-06-17 11:19 UTC, evgenyrodionov commented on complex.html
> +        <div class="complex-offers-cards-wrapper">
ты любишь врапперы, да?

2017-06-17 11:19 UTC, evgenyrodionov commented on complex.html
> +      <div class="grid-wrapper">
бляяяя

2017-06-17 11:19 UTC, evgenyrodionov commented on complex.html
> +      <div class="grid-wrapper">
это-то что означает?

2017-06-17 11:19 UTC, evgenyrodionov commented on style.css
> +/* complex page styles */
вынеси в отдельный файл

2017-06-17 11:58 UTC, nikolaevigor commented on complex.html
> +        <div class="complex-offers-cards-wrapper">
@evgenyrodionov с симпатией отношусь

2017-06-17 13:44 UTC, imevro approved these changes

2017-06-17 13:44 UTC, merged

2017-06-17 13:44 UTC, evgenyrodionov commented
Гит чекаут мастер, гит пулл ориджин мастер --ребейз