Move project to yard.moscow api
nikolaevigor/yard-frontend pull request #22
Opened 2017-07-04 23:18 UTC by nikolaevigor

2017-07-05 10:37 UTC, imevro requested changes

2017-07-05 10:37 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +function createCard({ id, name, location, shortDescription }: ComplexType, imageUrl: string) {
это не креате это рендер

2017-07-05 10:37 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +    get('/complexes').then(({ items = [] }) => {
поч фильтр убрал

2017-07-05 10:37 UTC, evgenyrodionov commented on src/Complexes/Show/ImageCarousel.jsx
> +      <FavButton>{imageIds.length} фотография</FavButton>
43 фотография

2017-07-05 10:37 UTC, evgenyrodionov commented on src/Complexes/Show/ImageCarousel.jsx
> +      <FavButton>{imageIds.length} фотография</FavButton>
плюралайзер сделай

2017-07-05 10:37 UTC, evgenyrodionov commented on src/Complexes/Show/Summary.jsx
>            предложений
201 предложений

2017-07-05 10:37 UTC, evgenyrodionov commented on src/Complexes/Show/Summary.jsx
>            предложений
ебал ее рука

2017-07-05 17:55 UTC, imevro requested changes

2017-07-05 17:55 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +    get('/complexes?filter[state]=public').then(({ items = [] }) => {
оно же не заработает

2017-07-05 17:55 UTC, evgenyrodionov commented on src/Complexes/Show/ImageCarousel.jsx
> +        {imageIds.length} {pluralize('фотограф', imageIds.length, ['ий', 'ия', 'ии'])}
плюралайзер компонентом сделай

2017-07-05 17:55 UTC, evgenyrodionov commented on src/Complexes/Show/ImageCarousel.jsx
> +        {imageIds.length} {pluralize('фотограф', imageIds.length, ['ий', 'ия', 'ии'])}
и вот это разделение на корень и окончания говно какое-то

2017-07-05 17:55 UTC, evgenyrodionov commented on src/utils.js
> +export { getImageUrl, pluralize };
сразу экспорт делай

2017-07-05 21:12 UTC, imevro requested changes

2017-07-05 21:12 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +    get(encodeURI('/complexes?filter[state]=public')).then(({ items = [] }) => {
А почему не в апи тогда уже?

2017-07-05 21:12 UTC, evgenyrodionov commented on src/Complexes/Show/ImageCarousel.jsx
> +        <Pluralizer num={imageIds.length} forms={['фотографий', 'фотография', 'фотографии']} />
передавать массив вместо нормальных очевидных пропов зашквар

one, few, other

2017-07-05 21:12 UTC, evgenyrodionov commented on src/Complexes/Show/ImageCarousel.jsx
> +        <Pluralizer num={imageIds.length} forms={['фотографий', 'фотография', 'фотографии']} />
num тоже говно нейминг

2017-07-05 21:12 UTC, evgenyrodionov commented on src/Complexes/Show/Summary.jsx
> +          {pluralize(units, ['предложений', 'предожениe', 'предложения'])}
и че где компонент?

2017-07-06 09:32 UTC, imevro requested changes

2017-07-06 09:32 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +function formatQuarter(quarter) {
я скидывал дикшенриес вообще-то

2017-07-06 09:32 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +  if (formattedFrom === formattedTo) {
ставь пустые строки между

2017-07-06 09:32 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +                <Value>Квартиры</Value>
это из апи надо брать

2017-07-06 09:32 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +                <Value>Охраняемая территория</Value>
из апи

2017-07-06 09:32 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +                <Value>Нет</Value>
из апи

2017-07-06 09:32 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +                <Value>{parkings} м/м</Value>
а может быть "нет"

2017-07-06 09:32 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +                <Name>Цены:</Name>
откуда тут двоеточие осталось

2017-07-06 09:32 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +          {() => {
https://facebook.github.io/react/docs/conditional-rendering.html

2017-07-06 17:11 UTC, imevro requested changes

2017-07-06 17:11 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +                <Value>{formatGarages(parkings)}</Value>
format**Garages**(**parkings**)

2017-07-06 17:11 UTC, evgenyrodionov commented on src/Complexes/dictionaries.jsx
> +export const offerKinds = {
где флоу

2017-07-06 23:46 UTC, imevro requested changes

2017-07-06 23:46 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +function formatParkings(parkingsAmount) {
а где флоу

2017-07-06 23:46 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +function formatParkings(parkingsAmount) {
вообще в этом файле мало флоу

2017-07-07 11:03 UTC, imevro requested changes

2017-07-07 11:03 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +  return Math.round(Number(number));
1) зачем тебе эта функция которая повторяет дефолтный Math.round
2) зачем приводить к числу если у тебя и так в флоу прописано что придет число

2017-07-07 11:03 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +function cutFloat(number: number, to = 2):string {
С to че?

2017-07-07 11:03 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +function formatParkings(parkingsAmount:number):string {
не проще пассить сразу `amount` btw?

2017-07-07 11:03 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
>    if (parkingsAmount || parkingsAmount === 0) {
если **есть** кол-во паркингов либо кол-во паркингов равно 0, то вернуть "Нет"?

2017-07-07 11:03 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +  const detailsDefaults = {
реакт будет создавать это каждый раз, а это статические данные

2017-07-07 11:03 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +function formatCeilHeight({ from, to }:{ from: number, to: number }):string {
у тебя же есть тайп рендж

2017-07-07 16:54 UTC, imevro approved these changes

2017-07-07 16:54 UTC, merged