Add carousel
nikolaevigor/yard-frontend pull request #25
Opened 2017-07-08 20:22 UTC by nikolaevigor

2017-07-08 21:38 UTC, evgenyrodionov commented
Завтра распишу всё

2017-07-08 21:38 UTC, evgenyrodionov commented on src/App.css
> +.carousel {
не оч осмысленное название, .modal-opened лучше будет

2017-07-11 20:02 UTC, nikolaevigor commented
https://yard-review-carousel.now.sh/complex/2

2017-07-11 21:26 UTC, evgenyrodionov commented
Чё-то желе какое-то при клике https://www.dropbox.com/s/vxxqu66tgcz65cx/screencast%202017-07-12%2000-23-39.mp4?dl=0

И растянуто:
![image](https://user-images.githubusercontent.com/775692/28091485-9a72829c-6698-11e7-9146-f31c15e96177.png)

Хотя на деле пикча такая:
![image](https://user-images.githubusercontent.com/775692/28091499-a5714b92-6698-11e7-8e7c-7b03028c553a.png)

Плюс не используй 512 в фуллскрине, 1024

2017-07-12 14:34 UTC, nikolaevigor commented
https://yard-review-carousel.now.sh/

2017-07-12 20:35 UTC, nikolaevigor commented
Добавил еще открытие нужной картинки по клику @evgenyrodionov

2017-07-12 20:46 UTC, evgenyrodionov commented
Кул

2017-07-13 09:07 UTC, evgenyrodionov commented
Доделывай, не вешай ревью пока не сделаешь

2017-07-22 16:53 UTC, nikolaevigor commented
build-zfthvcefgd.now.sh

2017-07-22 18:12 UTC, evgenyrodionov commented
У карточки внутри какие-то лютые отступы кстати

![image](https://user-images.githubusercontent.com/775692/28493623-70867f5a-6f22-11e7-97fb-acdc3d5947cc.png)

2017-07-22 18:15 UTC, imevro requested changes
сложно выглядит из-за логики ресайза

2017-07-22 18:15 UTC, evgenyrodionov commented on src/App.css
> +  overflow: hidden;
не понял зачемм

2017-07-22 18:15 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +    window.addEventListener('resize', this.updateWindowDimensions);
мне не нравится идея делать адаптив через ресайз эвент

2017-07-22 18:15 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +    window.addEventListener('resize', this.updateWindowDimensions);
это лишние вычисления

2017-07-22 18:15 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +                      if (idx > 0) {
вынеси эту проверку в онклик

2017-07-22 18:15 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +    let elementWidth, elementHeight;
БЕЗ МУТАБЕЛЬНОСТИ

2017-07-22 21:05 UTC, nikolaevigor commented
build-mwkdqpwiel.now.sh

2017-07-24 12:17 UTC, evgenyrodionov commented
Уехало
![image](https://user-images.githubusercontent.com/775692/28523020-3b0174e0-7083-11e7-8005-8210a6a29e61.png)

2017-07-24 12:18 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28523042-4fca5b12-7083-11e7-8fc6-a4dfc408df61.png)

2017-07-24 12:19 UTC, evgenyrodionov commented
И смотри, при ховере не очень очевидно что сейчас откроется галерея. Курсор поинтер, шаришь?

2017-07-24 12:50 UTC, nikolaevigor commented
build-rlfmphwung.now.sh

2017-07-24 12:50 UTC, nikolaevigor commented
при ховере я сделал опасити 0.9 и поинтер в предыдущем коммите

2017-07-24 22:59 UTC, imevro requested changes

2017-07-24 22:59 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +const animationDuration = '0.25s';
храни флоатом

2017-07-24 22:59 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +      items: [...Array(children.length).keys()].map(idx => {
я чё-то блядь не понял этого `[...Array(children.length).keys()]`

ЧТО ЭТО???????????????????????????????????????????????
????????????????????????????
ЗАЧЕМ?????????????????????????????????????????????????????????????

WHAT THE FUCK???????????????????????????????????????????????????????????

ПОЧЕМУ НЕ ПРОСТОЙ МАП??????????????????????????????????????????????????????????????????????

2017-07-24 22:59 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +      items: [...Array(children.length).keys()].map(idx => {
?????????????????????????????????????????

2017-07-24 22:59 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +      items: [...Array(children.length).keys()].map(idx => {
КАК ЭТО ДОЛЖНО РАБОТАТЬ??????????????

2017-07-24 22:59 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +      width: '0',
почему строкой? ты наркоман?

2017-07-24 22:59 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +    window.addEventListener('resize', this.updateWindowDimensions);
так я же говорил убрать, почему не убрал

2017-07-24 22:59 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +    this.setState({ width: window.innerWidth, height: window.innerHeight });
зачем в стейт класть? почему не можешь сразу обращаться? лол?

2017-07-24 22:59 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +  slide = (e, direction) => {
где флоу?

почему direction это булеан? почему не left/right? ты для кого пишешь код? сам как через полгода в этом будешь разбираться?

2017-07-24 22:59 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +      e.stopPropagation();
у тебя три (!) раза в трёх (!) разных методах встречается e.stopPropagation(). Не заебывает в голове хранить прописал ты или нет?

2017-07-24 22:59 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +      e.stopPropagation();
либо вешай на хэндлеры либо только в метод слайд

2017-07-24 22:59 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +              this.props.escHandler();
а если забыл передать?

2017-07-24 22:59 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +            onClick={e => {
сделай отдельный хэндлер

2017-07-25 01:04 UTC, nikolaevigor commented
build-apwgqgtxjc.now.sh

2017-07-25 09:30 UTC, imevro requested changes

2017-07-25 09:30 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +      items: children.map((item, idx) => ({ idx: initialIdxs[idx], image: children[idx] })),
не понял почему в image нельзя положить item, а в idx — idx?

2017-07-25 09:30 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +    const idxDelta = isRight ? 1 : -1;
без булеанов давай

2017-07-25 09:30 UTC, evgenyrodionov commented on src/Complexes/Show/ExtendedCarousel.jsx
> +    const idxDelta = isRight ? 1 : -1;
просто лефт или райт

2017-07-25 20:41 UTC, imevro approved these changes

2017-07-25 20:41 UTC, merged