Add adaptive complexes
nikolaevigor/yard-frontend pull request #29
Opened 2017-07-19 13:58 UTC by nikolaevigor

2017-07-19 17:49 UTC, nikolaevigor commented
build-flomhrldyd.now.sh

2017-07-20 09:41 UTC, imevro requested changes
https://github.com/boldyrev-d/yard-frontend/pull/14

2017-07-20 19:33 UTC, nikolaevigor commented
build-zgozynuqoj.now.sh

2017-07-21 18:09 UTC, evgenyrodionov commented
Исправь конфликты

2017-07-21 21:28 UTC, imevro requested changes

2017-07-21 21:28 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +import breakpoints from '../../breakpoints';
лучше в utils и назвать `media`

2017-07-21 21:28 UTC, evgenyrodionov commented on src/Header.jsx
> +  @media (max-width: 768px) {
а тут поч не БРЕЙКОИНТС

2017-07-21 21:28 UTC, evgenyrodionov commented on src/breakpoints.jsx
> +    @media (max-width: 768px) {
пересмотри видос про адаптив — mobile first, а не вот это вот

2017-07-22 09:49 UTC, imevro requested changes

2017-07-22 09:49 UTC, evgenyrodionov commented on src/utils.js
> +  toLg: (...args: any) => css`
убери все эти to*

2017-07-22 13:52 UTC, merged