Last block for complex.html
nikolaevigor/yard-frontend pull request #3
Opened 2017-06-16 17:14 UTC by nikolaevigor

Добавил последний блок, исправил косяки, до 12 добью кнопарь.

2017-06-16 17:49 UTC, nikolaevigor commented
Добавил кнопку

2017-06-16 21:50 UTC, evgenyrodionov commented
Не оч хорошо вышло https://www.dropbox.com/s/de5mmz2hudenikp/Screenshot%202017-06-17%2000.50.03.png?dl=0

2017-06-16 22:00 UTC, imevro requested changes

2017-06-16 22:00 UTC, evgenyrodionov commented on complex.html
> +    <div class="geo">
плохой нейминг, абсолютно неочевидный что это про комплекс

2017-06-16 22:00 UTC, evgenyrodionov commented on style.css
> +  flex-flow: column;
зачем?

2017-06-16 22:00 UTC, evgenyrodionov commented on style.css
> +  flex-flow: column;
читай про блочную модель и как себя ведут блоки

2017-06-17 10:44 UTC, imevro requested changes

2017-06-17 10:44 UTC, evgenyrodionov commented on complex.html
> +              <img class="nearby-image" src="./img/polyanka-photo.png" alt="Полянка">
что с отступом

2017-06-17 10:44 UTC, evgenyrodionov commented on complex.html
>      <div class="nearby">
почему nearby-то, а ниже complex-directions

2017-06-17 10:44 UTC, evgenyrodionov commented on complex.html
>      <div class="nearby">
тот же самый вопрос к карусели

2017-06-17 10:44 UTC, evgenyrodionov commented on complex.html
>      <div class="nearby">
приведи к одному виду

2017-06-17 11:08 UTC, imevro approved these changes

2017-06-17 11:09 UTC, merged

2017-06-17 11:09 UTC, evgenyrodionov commented
Гит пулл --ребейз в девелопе