Add adaptive complex
nikolaevigor/yard-frontend pull request #30
Opened 2017-07-22 23:43 UTC by nikolaevigor

2017-07-22 23:43 UTC, nikolaevigor commented
Глянь features, пожалуйста @evgenyrodionov

2017-07-24 10:00 UTC, nikolaevigor commented
build-piotwvlcin.now.sh

2017-07-24 10:54 UTC, imevro approved these changes
а так норм. доделывай.

2017-07-24 10:54 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +    &:first-child {
этого можно не делать, потому что mobile first — то что определено снизу, наследуется выше

2017-07-24 18:11 UTC, nikolaevigor commented
build-ijpkrhtxqz.now.sh

2017-07-24 22:48 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28548174-36c9e3c8-70db-11e7-817e-d237dd8d5c37.png)
![image](https://user-images.githubusercontent.com/775692/28548198-4c27acbe-70db-11e7-9cdb-8a1e8143ce4d.png)

2017-07-25 02:05 UTC, nikolaevigor commented
build-xanrzdflso.now.sh

2017-07-25 09:26 UTC, evgenyrodionov commented
Кнопка не работает + бордер у нее глупый

![image](https://user-images.githubusercontent.com/775692/28565298-78c1af50-7134-11e7-94ca-debb90716689.png)

2017-07-25 10:06 UTC, nikolaevigor commented
build-hajorxlmfe.now.sh

2017-07-25 20:32 UTC, evgenyrodionov commented
Поправь это наконец, стыдно же

![image](https://user-images.githubusercontent.com/775692/28592399-83e1e988-7191-11e7-9d72-0ebe143c724b.png)

2017-07-25 20:35 UTC, imevro requested changes

2017-07-25 20:35 UTC, evgenyrodionov commented on src/Complexes/Show/Description.jsx
> +    const { isExtended = false, fullDescription = '' } = this.state;
а зачем дескрипшен в стейт класть? к пропам обращайся

2017-07-25 20:35 UTC, evgenyrodionov commented on src/Complexes/Show/Description.jsx
> +    this.setState({ isExtended: !isExtended });
о нет, мой друг

https://medium.freecodecamp.org/functional-setstate-is-the-future-of-react-374f30401b6b
https://medium.com/@shopsifter/using-a-function-in-setstate-instead-of-an-object-1f5cfd6e55d1

2017-07-25 22:55 UTC, nikolaevigor commented on src/Complexes/Show/Description.jsx
> +    this.setState({ isExtended: !isExtended });
круто!

2017-07-25 23:02 UTC, nikolaevigor commented
build-vljgadrcmh.now.sh

2017-07-26 08:00 UTC, imevro approved these changes

2017-07-26 08:00 UTC, merged