Complexes page reimplemented via react
nikolaevigor/yard-frontend pull request #7
Opened 2017-06-19 14:16 UTC by nikolaevigor

2017-06-19 21:44 UTC, imevro requested changes
плохо с неймингом, префиксуешь слишком много.

реакт-компоненты должны быть с расширением .jsx, не .js

2017-06-19 21:44 UTC, evgenyrodionov commented on public/manifest.json
> +  "short_name": "React App",
стыдно же

2017-06-19 21:44 UTC, evgenyrodionov commented on src/Complex/ApartmentHeader.js
> +const ComplexApartmentHeader = styled.div`
а зачем

2017-06-19 21:44 UTC, evgenyrodionov commented on src/Complex/ApartmentHeader.js
> +const ComplexApartmentHeaderWrapper = styled.div`
писать

2017-06-19 21:44 UTC, evgenyrodionov commented on src/Complex/ApartmentHeader.js
> +const ComplexApartmentHeaderInfo = styled.div`
префикс

2017-06-19 21:44 UTC, evgenyrodionov commented on src/Complex/ApartmentHeader.js
> +const ComplexApartmentHeaderTitle = styled.h1`
комплекс

2017-06-19 21:44 UTC, evgenyrodionov commented on src/Complex/ApartmentHeader.js
> +const ComplexApartmentHeaderGeo = styled.p`
если ты

2017-06-19 21:44 UTC, evgenyrodionov commented on src/Complex/ApartmentHeader.js
> +const ComplexApartmentHeaderFavouritesButton = styled.button`
работаешь с комплексом

2017-06-19 21:44 UTC, evgenyrodionov commented on src/Complex/Complex.js
> +import "../App.css";
ты уже однажды заимпортил, нет нужды ещё раз его импортить

2017-06-19 21:44 UTC, evgenyrodionov commented on src/Complex/Description.js
> +          <Title text="Описание" />
используй пропсчилдрен

2017-06-19 21:44 UTC, evgenyrodionov commented on src/Complex/Features.js
> +              <Feature>
неправильная верстка, у тебя должен быть один элемент в одной колонке, потому что с апи тебе может приходить то 2 значения, то 20

2017-06-19 21:44 UTC, evgenyrodionov commented on src/Complexes/Cards.js
> +  margin: 64px 128px 96px 128px;
ремы для лохов или что?

2017-06-19 21:44 UTC, evgenyrodionov commented on src/Complexes/Cards.js
> +import Card from './Card.js'
можно опустить расширение если импортишь джс

2017-06-19 21:48 UTC, nikolaevigor commented on src/Complex/Complex.js
> +import "../App.css";
@evgenyrodionov а если тот файл удалят из проекта и останется только этот?

2017-06-20 11:06 UTC, imevro requested changes

2017-06-20 11:06 UTC, evgenyrodionov commented on src/Complex/ApartmentHeader.jsx
> +const ApartmentHeader = styled.div`
Игорь, если ты в апартаментхедер.джсх, смысл тут префиксовать?

2017-06-20 11:06 UTC, evgenyrodionov commented on src/Complex/ApartmentHeader.jsx
> +const ApartmentHeader = styled.div`
очевидно что это не комплекс хедер или дискавер нью девелопмент

2017-06-20 11:06 UTC, evgenyrodionov commented on src/Complex/Features.jsx
> +        <Records>
Records > Feature > FeatureName + FeatureValue?

2017-06-20 11:06 UTC, evgenyrodionov commented on src/Complex/Features.jsx
> +        <Records>
Records > Feature > FeatureName + FeatureValue?

2017-06-20 11:06 UTC, evgenyrodionov commented on src/Header.js
> +const LogoLink = styled(Link)``
поч нельзя сразу использовать линк? Смысл стилизовать?

2017-06-20 11:06 UTC, evgenyrodionov commented on src/Header.js
> +const NavLink = styled.a `
почему не линк из реакт-роутера?

2017-06-20 13:01 UTC, imevro approved these changes

2017-06-20 13:04 UTC, evgenyrodionov commented
По изменениям ок, теперь надо приводить структуру в порядок.
1) почисти от мусора
2) `Complex/Complex.jsx` слегка бессмысленное, если ты назовешь файл как `Complex/index.jsx`, то сможешь импортить просто как `import ... from './Complex'`
3) что будет, если у тебя будет 20 страниц на сайте? Ты будешь плодить `/Properties`, `/Property`, `/ControlPanel`, `/ControlPanelSettings`? Объединяй по бизнес-сущностям, не по страницам: не `/Complex` и `/Complexes`, а `/Complexes/List`, `/Complexes/Show`, потому что бизнес-сущность же ЖК

2017-06-20 21:25 UTC, imevro requested changes
чисти

2017-06-20 21:25 UTC, evgenyrodionov commented on src/App.css
> +.App-logo {
почисти

2017-06-20 21:25 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +      <CardThumbnail src={process.env.PUBLIC_URL + '/img/apartment_' + props.id +'.png'}/>
чё за префиксы

2017-06-20 21:25 UTC, evgenyrodionov commented on src/Complexes/List/Intro.jsx
> +            <IntroTitle>Discover Our New Developments</IntroTitle>
чисти эти префиксы

2017-06-20 21:25 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +          <Cards />
смотри чужие пр и посмотри почему это неправильно

2017-06-20 21:25 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +        <div>
зачем

2017-06-20 21:52 UTC, nikolaevigor commented on src/Complexes/List/index.jsx
> +          <Cards />
Если кто будет сюда смотреть, то
![teampaper snap_2017-06-21 00-51-26](https://user-images.githubusercontent.com/3702281/27357657-d22588b6-561b-11e7-8698-f91e06378b8c.png)

2017-06-21 09:30 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +          <Cards />
я про лишний компонент кардс, а не про див

2017-06-21 09:36 UTC, imevro requested changes

2017-06-21 09:36 UTC, evgenyrodionov commented on src/Footer.jsx
> +          <AllApartmentLink href="#">
не нравится нейминг

2017-06-21 09:36 UTC, evgenyrodionov commented on src/Footer.jsx
> +          <AllApartmentLink href="#">
а если я захочу такой же блок поставить в Компания? Типа "Наша история"

2017-06-21 09:36 UTC, evgenyrodionov commented on src/Footer.jsx
> +          <AllApartmentLink href="#">
Наша история: мы начали федеральное агентство недвижимости с комментария "виз хуяроу"

2017-06-21 09:36 UTC, evgenyrodionov commented on src/Header.jsx
> +          <Link to='/'>
поч ниже двойные а тут нет

2017-06-21 13:29 UTC, imevro requested changes

2017-06-21 13:29 UTC, evgenyrodionov commented on package.json
> +    "normalize": "^0.3.1",
Это не тот пакет))) сразу видно не умеешь искать официальный сайт)))

(((

2017-06-21 13:29 UTC, evgenyrodionov commented on package.json
> +    "react-body-classname": "^1.1.1",
а зачем он улетел в девдепс?

2017-06-21 13:29 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +  display: flex;
а зачем это? Карточки и так встанут вертикально нормально, а с помощью дисплей-флекс ты сломаешь сетку (грид, он же контейнер)

2017-06-21 13:37 UTC, imevro approved these changes
красава хули

2017-06-21 13:38 UTC, merged